### ISSUE TITLE
Failed to activate the atom-rails package

### ISSUE THREAD

**Issue by roblescoulter** [tomkadwill/atom-rails#17]
1. Started Mac OS X
2. Atom opened automatically
3. Error appeared

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-rails](https://github.com/tomkadwill/atom-rails) package, v0.4.0
### Stack Trace

Failed to activate the atom-rails package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/luisrobles/.atom/packages/atom-rails/lib/atom-rails.coffee:13:25)
    at Package.module.exports.Package.activateNow (/Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/luisrobles/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-rails, v0.4.0

# Dev
No dev packages
```

**Comment by adam-stokes** [comment]
Happens on atom 198 running with 1.0 api preview mode as well

**Comment by tomkadwill** [comment]
@RoblesCoulter and @battlemidget I'm closing this issue as the package is no longer supported or available. Sorry for the delay in getting back to you :)
