### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by ghost** [tomkadwill/atom-rails#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-rails](https://github.com/tomkadwill/atom-rails) package, v0.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/evrei/.atom/packages/atom-rails/lib/atom-rails.coffee:13

TypeError: Cannot read property 'getPath' of undefined
  at Object.module.exports.switchToModel (/Users/evrei/.atom/packages/atom-rails/lib/atom-rails.coffee:13:51)
  at atom-workspace.<anonymous> (/Users/evrei/.atom/packages/atom-rails/lib/atom-rails.coffee:9:66)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -0:01.9.0 atom-rails:switch-to-model (a.)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode",
      "goto",
      "goto",
      "html2jade",
      "html2jade",
      "html2jade",
      "git-blame",
      "gitignore-snippets"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-jshint, v2.0.0
atom-rails, v0.4.0
auto-update-packages, v0.2.2
color-picker, v1.7.0
compass, v0.9.1
emmet, v2.3.10
gitter, v0.6.2
html2haml, v0.10.0
language-gitignore, v0.2.0
language-haml, v0.20.0
language-jade, v0.4.0
linter-haml, v0.4.0
markdown-preview-plus, v1.4.0
meteor-api, v2.19.0
project-manager, v1.15.7
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0
terminal-status, v1.6.7
trailing-spaces, v0.2.5

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @Evrei, closing this because the package is no longer supported or available for Atom. Sorry for the delay in getting back to you :)
